version: "3.9"
services:
  server:
    build:
      context: ./web_analyzer_server
    ports:
      - "8080:8080"
    networks:
      - webnet

  client:
    build:
      context: ./web_analyzer_client
    ports:
      - "5000:80"
    depends_on:
      - server
    networks:
      - webnet

networks:
  webnet:
